name: kubernetes ci 
on:
  push:
    branches: 
      - main 
      
jobs:
  java-ci:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout 
        uses: actions/checkout@v4
      - name: Build docker image 
        run: "docker build -t raghavendra675/java:${GITHUB_SHA::7} ."
      - name: login docker   
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: push image to docker 
        run: "docker push raghavendra675/java:${GITHUB_SHA::7}"
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq  
      - name: update deploymnet.yml with latest tag   
        run: |
          #shot commit hash 
          SHORT_SHA=${GITHUB_SHA::7}
          # update image tag in deployment.yaml 
          yq -i '.spec.template.spec.containers[0].image = "raghavendra675/java:'"$SHORT_SHA"'"' k8s/deployment.yaml
      - name: commit deployment files
        run: | 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@noreply"
          git add Deployment.yaml
          git commit -m 'docker tags update BY GHA'
          git push origin main 

        
      
